"""Rush Hour — the second Daily Game plugin (pure, server-authoritative logic).

A 6×6 grid packed with cars (horizontal or vertical, length 2–3). Slide cars along their axis
(any distance = one move) to free the red target car out the exit on the right. Ranked by TIME
(continuous clock, like the pig); fewest moves breaks ties. Every daily board is generated by
BFS so it's guaranteed solvable and carries an exact optimal-move par.

Board payload:
  {"size": 6, "exit_row": 2, "target": "X",
   "cars": [{"id","r","c","len","orient"("h"|"v")}, ...]}
A move in a solution: [car_id, delta]  (delta = signed cells; +right/down, -left/up).
"""

from __future__ import annotations

import random
from collections import deque

ID = "rushhour"
NAME = "Rush Hour"
ICON = "🚗"
SURFACE = "web"
DIFFICULTIES = ["easy", "medium", "hard"]
RANK_ORDER = ("secondary_score", "primary_score")   # time first, moves break ties
HOWTO = (
    "Slide the cars to get the **red car** 🟥 out the exit on the right. Cars only move along "
    "their own direction (a slide of any length is **one move**) and can't pass through each "
    "other. Free the red car in as few moves as you can — but your rank is your **time** (the "
    "clock runs continuously across retries), so solve it fast. The clock starts on Start."
)

SIZE = 6
EXIT_ROW = 2
TARGET = "X"
# difficulty → (num cars incl. target, optimal-move range to accept)
_PARAMS = {
    "easy":   (7, (4, 9)),
    "medium": (9, (10, 18)),
    "hard":   (11, (19, 40)),
}


# ── board / state helpers ─────────────────────────────────────────────────────
def _var(car: dict) -> int:
    """The car's variable coordinate (column for horizontal, row for vertical)."""
    return car["c"] if car["orient"] == "h" else car["r"]


def _cells_at(car: dict, var: int) -> list[tuple[int, int]]:
    if car["orient"] == "h":
        return [(car["r"], var + k) for k in range(car["len"])]
    return [(var + k, car["c"]) for k in range(car["len"])]


def _occupied(cars: list[dict], state: tuple, exclude: int) -> set:
    occ = set()
    for i, car in enumerate(cars):
        if i == exclude:
            continue
        occ.update(_cells_at(car, state[i]))
    return occ


def _solved(cars: list[dict], state: tuple, target: int) -> bool:
    car = cars[target]
    return state[target] + car["len"] - 1 == SIZE - 1     # red car reached the right edge


def _neighbors(cars: list[dict], state: tuple, target: int):
    """Yield (next_state, (car_id, delta)) for every legal single slide (any distance)."""
    for i, car in enumerate(cars):
        occ = _occupied(cars, state, i)
        cur = state[i]
        maxv = SIZE - car["len"]
        # slide toward larger var (right/down), then smaller — stop at first blocked cell
        for step in (1, -1):
            v = cur + step
            while 0 <= v <= maxv:
                new_cell = _cells_at(car, v)[-1 if step > 0 else 0]
                if new_cell in occ:
                    break
                ns = list(state)
                ns[i] = v
                yield tuple(ns), (car["id"], v - cur)
                v += step


def solve(board: dict, want_path: bool = False):
    """BFS for the minimum number of moves to free the target. Returns the optimal move count
    (or None if unsolvable / search bound hit); with want_path=True returns (optimal, moves)."""
    cars = board["cars"]
    target = next(i for i, c in enumerate(cars) if c["id"] == board.get("target", TARGET))
    start = tuple(_var(c) for c in cars)
    if _solved(cars, start, target):
        return (0, []) if want_path else 0
    seen = {start}
    q = deque([start])
    parent = {start: None}
    bound = 400_000
    while q and len(seen) < bound:
        state = q.popleft()
        for ns, mv in _neighbors(cars, state, target):
            if ns in seen:
                continue
            seen.add(ns)
            parent[ns] = (state, mv)
            if _solved(cars, ns, target):
                depth = 0
                path = []
                cur = ns
                while parent[cur] is not None:
                    prev, mv2 = parent[cur]
                    path.append(list(mv2))
                    cur = prev
                    depth += 1
                path.reverse()
                return (depth, path) if want_path else depth
            q.append(ns)
    return (None, None) if want_path else None


# ── generation ────────────────────────────────────────────────────────────────
def _try_board(rng: random.Random, n_cars: int) -> dict | None:
    """Random valid packing with the target on the exit row. No solvability guarantee here —
    build_solvable filters with the BFS solver."""
    occ: set = set()
    cars: list[dict] = []
    # target: horizontal len-2 on the exit row, left of the exit
    tc = rng.randint(0, 3)
    for k in range(2):
        occ.add((EXIT_ROW, tc + k))
    cars.append({"id": TARGET, "r": EXIT_ROW, "c": tc, "len": 2, "orient": "h"})
    names = iter("ABCDEFGHIJKLMNOP")
    tries = 0
    while len(cars) < n_cars and tries < 400:
        tries += 1
        orient = rng.choice(["h", "v"])
        length = rng.choice([2, 2, 3])
        if orient == "h":
            r = rng.randint(0, SIZE - 1)
            c = rng.randint(0, SIZE - length)
            cells = [(r, c + k) for k in range(length)]
        else:
            r = rng.randint(0, SIZE - length)
            c = rng.randint(0, SIZE - 1)
            cells = [(r + k, c) for k in range(length)]
        if any(cell in occ for cell in cells):
            continue
        if r == EXIT_ROW and orient == "h":
            continue  # keep the exit row clear except the target
        occ.update(cells)
        cars.append({"id": next(names), "r": r, "c": c, "len": length, "orient": orient})
    return {"size": SIZE, "exit_row": EXIT_ROW, "target": TARGET, "cars": cars}


def build_solvable(seed: int, difficulty: str) -> dict:
    """Deterministically produce a GUARANTEED-solvable board whose optimal move count lands in the
    difficulty's range. Re-rolls the seed until the BFS solver approves; widens the range if a
    difficulty is stubborn so it always returns something."""
    n_cars, (lo, hi) = _PARAMS.get(difficulty, _PARAMS["medium"])
    for relax in range(0, 6):
        for attempt in range(400):
            rng = random.Random((seed + attempt * 2654435761 + relax * 40503) & 0xFFFFFFFF)
            board = _try_board(rng, n_cars)
            opt = solve(board)
            if opt is not None and (lo - relax) <= opt <= (hi + relax * 4):
                board["_par"] = opt
                return board
    raise RuntimeError("no solvable rush hour board found")


def par(puzzle: dict) -> tuple[int, bool]:
    """Exact optimal move count (BFS). approx=False — it's provably minimal."""
    if "_par" in puzzle:
        return puzzle["_par"], False
    opt = solve(puzzle)
    return (opt if opt is not None else 1), opt is None


def is_solvable(puzzle: dict) -> tuple[bool, list]:
    opt, path = solve(puzzle, want_path=True)
    return opt is not None, (path or [])


def _apply(cars_pos: dict, board: dict, car_id: str, delta: int) -> bool:
    """Apply one slide to a mutable {id: var} map. Returns False if illegal."""
    cars = {c["id"]: c for c in board["cars"]}
    car = cars.get(car_id)
    if car is None or delta == 0:
        return False
    cur = cars_pos[car_id]
    maxv = SIZE - car["len"]
    target = cur + delta
    if not (0 <= target <= maxv):
        return False
    others = set()
    for cid, c in cars.items():
        if cid == car_id:
            continue
        others.update(_cells_at(c, cars_pos[cid]))
    step = 1 if delta > 0 else -1
    v = cur
    while v != target:
        v += step
        edge = _cells_at(car, v)[-1 if step > 0 else 0]
        if edge in others:
            return False
    cars_pos[car_id] = target
    return True


def validate(puzzle: dict, solution: dict) -> dict | None:
    moves = solution.get("moves") or []
    if not isinstance(moves, list) or len(moves) > 200:
        return None
    pos = {c["id"]: _var(c) for c in puzzle["cars"]}
    for mv in moves:
        if not isinstance(mv, (list, tuple)) or len(mv) != 2:
            return None
        if not _apply(pos, puzzle, str(mv[0]), int(mv[1])):
            return None
    car = next(c for c in puzzle["cars"] if c["id"] == puzzle["target"])
    if pos[car["id"]] + car["len"] - 1 != SIZE - 1:
        return None
    return {"solved": True, "primary": len(moves), "secondary": 0}


def share_grid(result: dict, meta: dict) -> str:
    num = meta.get("number")
    par_v = meta.get("par")
    secs = result["secondary"] // 1000
    t = f"{secs // 60}:{secs % 60:02d}"
    head = f"🚗 Rush Hour #{num}" if num else "🚗 Rush Hour"
    par_str = f" (par {par_v})" if par_v is not None else ""
    return f"{head} · {meta.get('difficulty', '')} · {t} · {result['primary']} moves{par_str}\n🟥🏁"
